### ISSUE TITLE
Our bob.nightlies are failing on macosx

### ISSUE THREAD

**Issue by tiagofrepereira2012** [bioidiap/bob.io.image#9]
I just pushed the last 10 commits and the CI is failing on MacOSX

  https://gitlab.idiap.ch/biometric/bob.nightlies/builds/2473
  https://gitlab.idiap.ch/biometric/bob.nightlies/builds/2470

**Comment by siebenkopf** [comment]
It seems that the clang compiler has changed. For some reason it expects that it builds a C-only module, while the source code is actually C++. File a bug at clang!

**Comment by siebenkopf** [comment]
Hmm... I now see, why it thinks it is C code. The file to compile is called ``bob/io/image/pnmio.c``. Renaming it to ``bob/io/image/pnmio.cpp`` (similar to all the other files inside ``bob.io.image``) should solve the issue.

**Comment by 183amir** [comment]
I added pnmio.c it should be a C code not C++

**Comment by 183amir** [comment]
This looks like to be a bug where bob.extension adds an incorrect flag to C
files. This used to be a warning but looks like now it's an error.

**Comment by siebenkopf** [comment]
I see. AFAIR, the problem is that the python compilation always uses the ``CFLAGS`` to compile the extensions, not the ``CPPFLAGS`` or ``CXXFLAGS``. Hence, in order to be able to use the ``std-c++11`` features, we need to pass this flag to the compilations of the python bindings.

Anyways, you are compiling some C library code into the python ``Extension``. Maybe the solution is to use a ``Library`` extension: https://github.com/bioidiap/bob.extension/blob/master/bob/extension/__init__.py#L448
which compiles the code with ``CMake``, where we can control the flags (although I assume that I might also pass the wrong ``CFLAGS`` there, but this can be fixed if needed).

Another solution would be to put the whole ``pnmio.c`` into a ``extern C`` environment and compile it with the C++ compiler -- i.e., by renaming it to ``pnmio.cpp``.

**Comment by 183amir** [comment]
I think renaming would be the easiest. Please go ahead and rename it.

**Comment by tiagofrepereira2012** [comment]
It is already running on ci.
Will work, I used the mac-mini to test it, so I will close this one.
